name: Composer (php-actions)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clear composer cache
        uses: php-actions/composer@v6
        with:
          composer_version: 2
          command: clearcache

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          composer_version: 2
          php_version: 7.4
          command: composer update